---
ID: "63a40ef2-56db-4741-be88-91acb4793b35"
Parent: "8a69ff04-223f-4b3b-825e-1bc5ff6b6003"
Template: "8a69ff04-223f-4b3b-825e-1bc5ff6b6003"
Path: /sitecore/templates/Project/company/BookingServices/Rendering Parameters/BookingService Parameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4388a2df-add7-4315-864c-3202c919e5a4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\vasu_goyal@epam.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250402T092939Z
